### ISSUE TITLE
xdg_prop attribute

### ISSUE THREAD

**Issue by benureau** [GMvandeVen/brain-inspired-replay#2]
Perhaps related to 9afa20f14, I get:

```python
./compare_MNIST_hyperParams.py --scenario=task --seed=11                 #--> Fig. S1 (top)
Traceback (most recent call last):
  File "./compare_MNIST_hyperParams.py", line 62, in <module>
    args = handle_inputs()
  File "./compare_MNIST_hyperParams.py", line 37, in handle_inputs
    options.set_defaults(args, **kwargs)
  File "/home/fcyb/projects/brain-inspired-replay/options.py", line 350, in set_defaults
    args.xdg_prop = 0. if args.scenario=="task" and args.xdg_prop is None else args.xdg_prop
AttributeError: 'Namespace' object has no attribute 'xdg_prop'
```

Seems in `hyper` compare mode, `xdg_prop` is never defined?
https://github.com/GMvandeVen/brain-inspired-replay/blob/e9694e854429cc33c4ccb352a75099cc8d55ee4c/options.py#L259-L260

**Comment by GMvandeVen** [comment]
Yes, you're right. Thanks a lot for letting me know!
I just corrected the error so hopefully it should work now, but please let me know if you encounter any other issues.
